# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5aa3e8c3a043ab99906c531dabe8e701eee9665873161d7d8d39dc6e615a043ffa2298acc95957446f659cf294e6cda7ca7b46cb1e4c0cf45e96321702180f2

test:
  secret_key_base: 96266bcc92f44c686c8d139beecf279287da8cecc05f4a26f26bd87f2d028f6af70b09ee8b732821629c0a904e8e92a4c7e67e74de573dc22b2e55d18196c212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
